# Cluster Settings
cluster_vip: "192.168.255.50"
gateway_public: "192.168.130.254"

# Network IDs (Used by the trunk logic)
vlan_ids:
  public: 20
  private: 30
  internal: 40

# Addon Versions
versions:
  kubernetes: "1.34"        # Major.Minor for Apt Repo
  kubernetes_full: "1.34.4" # Full patch version for Kubeadm/Kubelet
  kube_vip: "v0.9.1"
  pause: "3.10"
  cilium: "1.18.4"
  cilium_cli: "v0.18.9"
  istio: "1.28.1"
  metallb: "v0.15.3"
  gateway_api_crd: "v1.4.0"
  nerdctl: "1.7.7"
# Default Behavior: All nodes are schedulable (workers) unless overridden

k8s_schedulable: true

cilium_config:
  bpf_masquerade: true
  loadbalancer_alg: "maglev"

system_config:
  enable_swap: false # Explicit toggle
  install_nerdctl: true

# Security
etcd_encryption_enabled: true
