---
- name: "Full Stack Validation Suite"
  hosts: masters[0]
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  vars:
    test_ns: "validation-test"
    test_domain: "smoke.test.local"
    # The Admin VIP you configured in group_vars/all.yml
    admin_vip: "192.168.255.50"

  tasks:
    # ==========================================================================
    # PHASE 1: INFRASTRUCTURE & OBSERVABILITY HEALTH
    # ==========================================================================
    - name: "Health: Check Node Status"
      shell: kubectl get nodes -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
      register: node_status
      failed_when: "'False' in node_status.stdout or 'Unknown' in node_status.stdout"
      changed_when: false

    - name: "Health: Verify Critical DaemonSets"
      kubernetes.core.k8s_info:
        kind: DaemonSet
        namespace: "{{ item.ns }}"
        name: "{{ item.name }}"
      register: ds_status
      loop:
        - { name: "cilium", ns: "kube-system" }
        - { name: "ztunnel", ns: "istio-system" }
        - { name: "speaker", ns: "metallb-system" }
        - { name: "istio-cni-node", ns: "istio-system" }
      failed_when: >
        ds_status.resources | length == 0 or
        ds_status.resources[0].status.numberReady < ds_status.resources[0].status.desiredNumberScheduled

    - name: "Observability: Verify Metrics Server Data"
      shell: kubectl top nodes --no-headers
      register: metrics_check
      retries: 6
      delay: 10
      until: metrics_check.rc == 0
      changed_when: false

    # ==========================================================================
    # PHASE 2: GATEWAY & IP ASSIGNMENT
    # ==========================================================================
    - name: "Ingress: Verify Gateway Class is Accepted"
      kubernetes.core.k8s_info:
        api_version: gateway.networking.k8s.io/v1
        kind: GatewayClass
        name: istio
      register: gw_class
      failed_when: >
        gw_class.resources | length == 0 or
        gw_class.resources[0].status.conditions | selectattr('type', 'equalto', 'Accepted') | selectattr('status', 'equalto', 'True') | list | length == 0

    - name: "Ingress: Verify Main Gateway has MetalLB IP"
      kubernetes.core.k8s_info:
        api_version: gateway.networking.k8s.io/v1
        kind: Gateway
        namespace: istio-system
        name: main-gateway
      register: gateway_info
      failed_when: >
        gateway_info.resources | length == 0 or
        gateway_info.resources[0].status.addresses is not defined or
        gateway_info.resources[0].status.addresses | length == 0

    - name: "Ingress: Capture Gateway IP"
      set_fact:
        gateway_ip: "{{ gateway_info.resources[0].status.addresses[0].value }}"

    # ==========================================================================
    # PHASE 3: AMBIENT MESH DEPLOYMENT
    # ==========================================================================
    - name: "Test: Create Namespace (Ambient Enabled)"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ test_ns }}"
            labels:
              istio.io/dataplane-mode: ambient

    - name: "Test: Deploy Curl Client (for internal testing)"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: curl-client
            namespace: "{{ test_ns }}"
            labels:
              app: curl
          spec:
            containers:
            - name: curl
              image: curlimages/curl
              command: ["/bin/sleep", "3600"]

    - name: "Test: Deploy Httpbin (Server)"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: httpbin
            namespace: "{{ test_ns }}"
            labels:
              app: httpbin
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: httpbin
            template:
              metadata:
                labels:
                  app: httpbin
              spec:
                containers:
                - name: httpbin
                  image: mccutchen/go-httpbin
                  ports:
                  - containerPort: 8080

    - name: "Test: Deploy Service"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: httpbin
            namespace: "{{ test_ns }}"
          spec:
            selector:
              app: httpbin
            ports:
            - port: 80
              targetPort: 8080

    - name: "Test: Deploy HTTPRoute (Gateway API)"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          metadata:
            name: httpbin-route
            namespace: "{{ test_ns }}"
          spec:
            parentRefs:
            - name: main-gateway
              namespace: istio-system
            hostnames:
            - "{{ test_domain }}"
            rules:
            - matches:
              - path:
                  type: PathPrefix
                  value: /
              backendRefs:
              - name: httpbin
                port: 80

    - name: "Test: Wait for Pods Ready"
      shell: "kubectl wait --for=condition=Ready pod --all -n {{ test_ns }} --timeout=60s"

    # ==========================================================================
    # PHASE 4: SECURITY & TRAFFIC VERIFICATION
    # ==========================================================================

    # --- POSITIVE TEST (Should Succeed) ---
    - name: "Traffic: Verify External Access (MetalLB -> Gateway -> Pod)"
      uri:
        url: "http://{{ gateway_ip }}/headers"
        headers:
          Host: "{{ test_domain }}"
        return_content: yes
        status_code: 200
      register: curl_result
      retries: 10
      delay: 3
      delegate_to: localhost
      become: no

    # --- NEGATIVE TEST (Should Fail / Timeout) ---
    - name: "Security: Verify Admin Network Isolation (Pod -> Admin VIP)"
      command: >
        kubectl exec -n {{ test_ns }} curl-client -- curl -m 3 -s -o /dev/null -w "%{http_code}" http://{{ networks.admin.prefix }}.{{ admin_vip }}:6443
      register: security_test
      # We EXPECT this to fail (rc != 0) OR return 000 (timeout)
      failed_when: security_test.rc == 0 and security_test.stdout != "000"
      ignore_errors: yes

    - name: "Result: Display Validation Summary"
      debug:
        msg:
          - "✅ GATEWAY: Traffic routed successfully through Istio Ambient."
          - "   Gateway IP: {{ gateway_ip }}"
          - "✅ SECURITY: Admin Network Isolation Check"
          - "   Result: {{ 'PASSED (Access Blocked)' if security_test.rc != 0 or security_test.stdout == '000' else 'FAILED (Access Allowed!)' }}"
          - "✅ METRICS: Metrics Server is reporting data."

    # ==========================================================================
    # PHASE 5: CLEANUP
    # ==========================================================================
    - name: "Cleanup: Remove Test Namespace"
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: "{{ test_ns }}"
