[masters]
# --- VM NODES (Standard Mode) ---
# They use the defaults: enX0, enX1, etc.
k8s-node-01 ansible_host=192.168.130.11 admin_ip=192.168.255.131 public_ip=192.168.130.11 private_ip=192.168.110.11 internal_ip=192.168.100.11 mode=standard
k8s-node-02 ansible_host=192.168.130.12 admin_ip=192.168.255.128 public_ip=192.168.130.12 private_ip=192.168.110.12 internal_ip=192.168.100.12 mode=standard

# --- BARE METAL NODE (Trunk Mode) ---
# Defines the parent wire (eno1). Ansible will create vlan.20, vlan.30 on top.
k8s-node-03 ansible_host=192.168.130.99 admin_ip=192.168.255.199 public_ip=192.168.130.99 private_ip=192.168.110.99 internal_ip=192.168.100.99 mode=trunk trunk_parent=eno1

[workers]

[k8s_cluster:children]
masters
workers

[all:vars]
ansible_user=debian
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
