[masters]
# --- VM NODES (Standard Mode) ---
# node_id: Defines the last octet for ALL networks (e.g., .11)
k8s-node-01 ansible_host=192.168.130.11 node_id=11 mode=standard
k8s-node-02 ansible_host=192.168.130.12 node_id=12 mode=standard

# --- BARE METAL NODE (Trunk Mode) ---
k8s-node-03 ansible_host=192.168.130.99 node_id=99 mode=trunk trunk_parent=eno1

[workers]
# Example worker
# k8s-worker-01 ansible_host=192.168.130.21 node_id=21 mode=standard

[k8s_cluster:children]
masters
workers

[all:vars]
ansible_user=debian
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
